# Generated by Django 5.0.2 on 2024-05-14 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aname', models.CharField(max_length=100, verbose_name='نوع العمل / نشاط')),
            ],
            options={
                'verbose_name': 'نشاط/عمل المتدرب',
                'verbose_name_plural': 'نشاط/عمل المتدرب',
                'ordering': ['aname'],
            },
        ),
        migrations.CreateModel(
            name='bmr_a',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bmr_a', models.FloatField(default=0.0, verbose_name='a')),
            ],
            options={
                'verbose_name': 'bmr_a',
                'verbose_name_plural': 'bmr_a',
            },
        ),
        migrations.CreateModel(
            name='bmr_b',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bmr_b', models.FloatField(default=0.0, verbose_name='b')),
            ],
            options={
                'verbose_name': 'bmr_b',
                'verbose_name_plural': 'bmr_b',
            },
        ),
        migrations.CreateModel(
            name='bmr_c',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bmr_c', models.FloatField(default=0.0, verbose_name='c')),
            ],
            options={
                'verbose_name': 'bmr_c',
                'verbose_name_plural': 'bmr_c',
            },
        ),
        migrations.CreateModel(
            name='bmr_d',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bmr_d', models.FloatField(default=0.0, verbose_name='d')),
            ],
            options={
                'verbose_name': 'bmr_d',
                'verbose_name_plural': 'bmr_d',
            },
        ),
        migrations.CreateModel(
            name='Bodytype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bname', models.CharField(max_length=100, verbose_name='طبيعة الجسم')),
            ],
            options={
                'verbose_name': 'طبيعة الجسم',
                'verbose_name_plural': 'طبيعة الجسم',
            },
        ),
        migrations.CreateModel(
            name='Evaluchoice',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('evalgradename', models.CharField(max_length=100, verbose_name='درجة التقييم')),
            ],
            options={
                'verbose_name': 'درجات التقييم',
                'verbose_name_plural': 'درجات التقييم',
                'ordering': ['evalgradename'],
            },
        ),
        migrations.CreateModel(
            name='FCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catname', models.CharField(max_length=100, verbose_name='اسم الصنف')),
                ('catlatinename', models.CharField(blank=True, max_length=100, verbose_name='اسم الصنف بالانكليزي')),
                ('catcontent', models.TextField(blank=True, null=True, verbose_name='المحتويات و التفاصيل')),
            ],
            options={
                'verbose_name': 'أصناف الأغذية',
                'verbose_name_plural': 'أصناف الأغذية',
            },
        ),
        migrations.CreateModel(
            name='Theaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ainame', models.CharField(max_length=100, verbose_name='هدف المتدرب')),
            ],
            options={
                'verbose_name': 'هدف المتدرب',
                'verbose_name_plural': 'هدف المتدرب',
                'ordering': ['ainame'],
            },
        ),
        migrations.CreateModel(
            name='Trainner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tname', models.CharField(max_length=100, verbose_name='اسم المدرب')),
                ('tlatinname', models.CharField(blank=True, max_length=100, null=True, verbose_name='اسم المدرب بالانكليزي')),
                ('age', models.IntegerField(default=14, verbose_name='العمر')),
                ('gender', models.CharField(choices=[('ذكر', 'ذكر'), ('انثى', 'انثى')], default='ذكر', max_length=9, verbose_name='الجنس')),
                ('weight', models.IntegerField(blank=True, default=20, null=True, verbose_name='الوزن')),
                ('height', models.IntegerField(blank=True, default=150, null=True, verbose_name='الطول')),
                ('timage', models.ImageField(blank=True, null=True, upload_to='Trainnerphotos/%y/%m/%d', verbose_name='صورة المدرب')),
                ('certificate', models.ImageField(blank=True, null=True, upload_to='TrainnerCerti/%y/%m/%d', verbose_name='صورة شهادة المدرب')),
                ('Trainee_track', models.BooleanField(blank=True, default=True, null=True, verbose_name='فعال')),
                ('content', models.TextField(blank=True, null=True, verbose_name='التفاصيل')),
                ('salary', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=6, null=True, verbose_name='الراتب')),
                ('joined_date', models.DateField(blank=True, null=True, verbose_name='تاريخ مباشرة')),
            ],
            options={
                'verbose_name': 'المدربين',
                'verbose_name_plural': 'المدربين',
                'ordering': ['tname'],
            },
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wname', models.CharField(max_length=100, verbose_name='اسم الحركة')),
                ('wimage', models.ImageField(blank=True, null=True, upload_to='Traineephotos/%y/%m/%d', verbose_name='صورة الحركة')),
                ('wtimes', models.IntegerField(default=12, verbose_name='عدد الدقائق/عدد تكرار الحركة')),
            ],
            options={
                'verbose_name': 'برنامج التدريب',
                'verbose_name_plural': 'برنامج التدريب',
                'ordering': ['wname'],
            },
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100, verbose_name='الاسم')),
                ('latinname', models.CharField(blank=True, max_length=100, null=True, verbose_name='الاسم بالانكليزي')),
                ('fats', models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='الدهون')),
                ('carbohydrates', models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='الكربوهيدرات/النشويات')),
                ('protein', models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='البروتينات')),
                ('calories', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='السعرات الحرارية')),
                ('image', models.ImageField(blank=True, upload_to='foodphotos/%Y/%m/%d', verbose_name='الصورة')),
                ('content', models.TextField(blank=True, null=True, verbose_name='المحتويات و التفاصيل')),
                ('active', models.BooleanField(default=True, verbose_name='فعال')),
                ('breakfast', models.BooleanField(default=True, verbose_name='الافطار')),
                ('lunch', models.BooleanField(default=True, verbose_name='الغداء')),
                ('dinner', models.BooleanField(default=True, verbose_name='العشاء')),
                ('fcat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='foods.fcategory', verbose_name='الصنف')),
            ],
            options={
                'verbose_name': 'الأغذية',
                'verbose_name_plural': 'الأغذية',
                'ordering': ['fname'],
            },
        ),
        migrations.CreateModel(
            name='Trainee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tename', models.CharField(max_length=100, verbose_name='اسم المتدرب')),
                ('tlatinname', models.CharField(blank=True, max_length=100, null=True, verbose_name='اسم المتدرب بالانكليزي')),
                ('age', models.IntegerField(default=14, verbose_name='العمر')),
                ('gender', models.CharField(choices=[('ذكر', 'ذكر'), ('انثى', 'انثى')], default='ذكر', max_length=9, verbose_name='الجنس')),
                ('weight', models.FloatField(blank=True, default=0.0, null=True, verbose_name='الوزن')),
                ('height', models.FloatField(blank=True, default=0.0, null=True, verbose_name='الطول')),
                ('teimage', models.ImageField(blank=True, null=True, upload_to='Traineephotos/%y/%m/%d', verbose_name='صورة المتدرب')),
                ('infection', models.ImageField(blank=True, null=True, upload_to='Traineev/%y/%m/%d', verbose_name='صورة اصابة المتدرب ان وجدت')),
                ('Trainee_active', models.BooleanField(blank=True, default=True, null=True, verbose_name='فعال')),
                ('tecontent', models.TextField(blank=True, null=True, verbose_name='التفاصيل')),
                ('subsciption_fee', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=6, null=True, verbose_name='رسم الاشتراك الشهري')),
                ('tejoined_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الاشتراك')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='بدأ من تاريخ ')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='الى تاريخ ')),
                ('bmr_value', models.FloatField(blank=True, default=0.0, null=True, verbose_name='السعرات الحرارية المطلوبة')),
                ('total_nitrution', models.FloatField(blank=True, null=True, verbose_name='مجموع السعرات')),
                ('a', models.ForeignKey(default=88.362, on_delete=django.db.models.deletion.DO_NOTHING, to='foods.bmr_a', verbose_name=' + (bmr_a)')),
                ('activities_work', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='foods.activities', verbose_name='نشاط / العمل')),
                ('aimoftrainee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='foods.theaim', verbose_name='الهدف')),
                ('b', models.ForeignKey(default=13.397, on_delete=django.db.models.deletion.DO_NOTHING, to='foods.bmr_b', verbose_name='+( الوزن bmr_b X)')),
                ('bodytypet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='foods.bodytype', verbose_name='طبيعة الجسم')),
                ('c', models.ForeignKey(default=4.799, on_delete=django.db.models.deletion.DO_NOTHING, to='foods.bmr_c', verbose_name='+( الارتفاع bmr_c X)')),
                ('d', models.ForeignKey(default=5.677, on_delete=django.db.models.deletion.DO_NOTHING, to='foods.bmr_d', verbose_name='-( العمر bmr_d X)')),
                ('nitrution_breakfast', models.ManyToManyField(related_name='الفطور', to='foods.food', verbose_name='الفطور')),
                ('nitrution_dinner', models.ManyToManyField(related_name='العشاء', to='foods.food', verbose_name='العشاء')),
                ('nitrution_lunch', models.ManyToManyField(related_name='الغداء', to='foods.food', verbose_name='الغداء')),
                ('workout', models.ManyToManyField(to='foods.workout', verbose_name='برنامج التدريب')),
            ],
            options={
                'verbose_name': 'المتدربين',
                'verbose_name_plural': 'المتدربين',
                'ordering': ['tename'],
            },
        ),
        migrations.CreateModel(
            name='PaymentTrainee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الدفعة')),
                ('pay_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='مقدار الدفعة')),
                ('traineepay', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='foods.trainee', verbose_name='المتدرب')),
            ],
            options={
                'verbose_name': 'المدفوعات',
                'verbose_name_plural': 'المدفوعات',
                'ordering': ['traineepay'],
            },
        ),
        migrations.CreateModel(
            name='Evaluationt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eval_date', models.DateField(blank=True, null=True, verbose_name='تاريخ التقييم')),
                ('eval_points', models.IntegerField(default=14, verbose_name='نقاط التقييم')),
                ('eval_grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='foods.evaluchoice', verbose_name='درجة التقييم')),
                ('tename', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='foods.trainee', verbose_name='اسم المتدرب')),
            ],
            options={
                'verbose_name': 'التقييم',
                'verbose_name_plural': 'التقييم',
                'ordering': ['tename'],
            },
        ),
        migrations.AddConstraint(
            model_name='trainee',
            constraint=models.CheckConstraint(check=models.Q(('total_nitrution__lt', models.F('bmr_value'))), name='مجموع السعرات الحرارية في الأغذية أكبر من اللازم BMR'),
        ),
    ]
